[[default]]
names = ["zsh", "foot", "sway", "mako"]
to = "~/.config"

[[default]]
name = "tmux.conf"
to = "~/.tmux.conf"


[[macOS]]
names = ["zsh", "foot"]
to = "~/.config"

[[macOS]]
name = "tmux.conf"
to = "~/.tmux.conf"
