[presets.base]
links = [
  "zsh",
  "foot",
  "sway",
  "mako",
  { name = "tmux.conf", to = "~/.tmux.conf" }
]
to = "~/.config"

[presets.macOS]
links = [
  "zsh",
  "foot",
  { name = "tmux.conf", to = "~/.tmux.conf" }
]
to = "~/.config"
